### ISSUE TITLE
You can't use `\unpenalty' in vertical mode

### ISSUE THREAD

**Issue by bernarpa** [sdaps/sdaps-class#1]
I was trying to compile a simple SDAPS document with the new class (sdapsclassic) and I got the error _You can't use `\unpenalty' in vertical mode_. Please note that after removing the two text boxes the example compiles well.

TeX example: http://pastebin.com/Q5pFSNxY
LaTeX log: http://pastebin.com/v6N68k8H

**Comment by benzea** [comment]
So the issue here is to define and implement how the choicequestion should behave like if it is adjacent to normal paragraphs.

At some point I was thinking of trying to get a mode where it behaves more like it was a line inside the next/previous paragraph rather than a paragraph on its own (i.e. no parskip after/before unless the user added an explicit empty line). This is not quite working and causing trouble in this case though.

**Comment by benzea** [comment]
It'll also compile fine if you add newlines throughout the document. i.e. in front of

    \begin{choicegroup}{A date}

**Comment by benzea** [comment]
Actually, it is the code that does the paragraph handling for the textboxes that is broken. Not the choicequestion (there the consideration is quite boring).

**Comment by benzea** [comment]
I decided to just remove all that crap. Not ideal but I don't expect that people actually figure out that there is a difference between having a blank line and not having one before/after a textbox. Not that you ever see it when using the sdapsclassic class.

The commit breaking it was 103f9aaf8c004439d1afdc58f33847052193ea52 the commit fixing it again is 67a81085f3f1f54bbdab26e41bdcdb738ed78603.

**Comment by bernarpa** [comment]
Thanks!
